---
title: "OPTIMUM"
author: "Dègninou Yehadji"
date: "04/05/2023"
output:
  html_document: default
  word_document: default
  pdf_document: default
---

```{r setup, echo=FALSE, include=FALSE}
## Chargement des packages 
library(knitr)
library(corrplot)
library(afex)
library(psych)
library(Hmisc)
library(ggeffects)
library(questionr)
library(expss)
library(RColorBrewer)
library(MASS)
library(MuMIn)
library(nortest)
library(mosaic)    # Load additional packages here 
library(ggformula) # formula interface to ggplot2
library(png)
library(grid)
library(dplyr)
library(lme4)
library(RVAideMemoire)
library(lattice)
library(ggplot2)
library(phia)
library(gridExtra)
library(ggsignif)
library(tidyr)
library(LMERConvenienceFunctions)    # outliers 
library(vctrs)
library(Rcpp)
library(nloptr)
library(shiny)
library(fmsb)
library(arsenal)
library(Gmisc)
library(cowplot)
library(pwr)
library(MatchIt)
library(optmatch)
library(lubridate)
library(purrr)
library(stringr)
tidy = FALSE     # display code as typed
size = "large"
```

```{r, echo=FALSE, include=FALSE}
## Set working directory
setwd("H:/My Drive/Acacia Tools/OPTIMUM/csvdata")
```

```{r, echo=FALSE, include=FALSE}
## create dataframe 
# Load the readxl package
# library(readxl)

# Read Excel files
Consult <- readxl::read_excel("consult.xlsx", na = c("", " ", "NA"))
Hospit <- readxl::read_excel("hospit.xlsx", na = c("", " ", "NA"))
Hosp_ant <- readxl::read_excel("hospit_anterieures.xlsx", na = c("", " ", "NA"))
OPTI <- readxl::read_excel("optimum.xlsx", na = c("", " ", "NA"))   
Symptome <- readxl::read_excel("questionnaire_symptome.xlsx", na = c("", " ", "NA"))

```

```{r, echo=FALSE, include=TRUE}
OPTI$DATE_DEB <-
  as.Date(OPTI$DMG_date_entree_optimum, format = "%m/%d/%Y")
OPTI$DATE_SORT <- as.Date(OPTI$SORT_date_sortie, format = "%m/%d/%Y")
OPTI$DATE_NAISSANCE <- as.Date(OPTI$BIRTH_DATE, format = "%m/%d/%Y")

OPTI$AGE <-
  difftime(OPTI$DATE_DEB, OPTI$DATE_NAISSANCE, units = "days")
OPTI$AGE <- round(as.numeric(OPTI$AGE / 365))

OPTI$SUIVI <- difftime(OPTI$DATE_SORT, OPTI$DATE_DEB, units = "days")
OPTI$SUIVI <- as.numeric(OPTI$SUIVI)
#OPTI$SEXE <-

# Car. inclusion
OPTI$EC_poids <- as.numeric(as.character(OPTI$EC_poids))
OPTI$EC_taille <- as.numeric(as.character(OPTI$EC_taille))

OPTI$TAILLE <- OPTI$EC_taille / 100
OPTI$POIDS_EC <- OPTI$EC_poids
OPTI$IMC <- (OPTI$EC_poids / OPTI$TAILLE ^ 2)

OPTI$PAS <- OPTI$EC_pas
OPTI$PAD <- OPTI$EC_pad
OPTI$NYHA <- OPTI$EC_nyha
OPTI$FC <- OPTI$EC_fc

# Car. cardio
OPTI$FDR_TABAC <- OPTI$FDRC_tabagisme
OPTI$FDR_DIABETE <- OPTI$FDRC_diabete
OPTI$FDR_HTA <- OPTI$FDRC_hta
OPTI$FDR_DYSLIPIDEMIE <- OPTI$FDRC_dyslipidemie
OPTI$FDR_HEREDITE_CORO <- OPTI$FDRC_hered_coro
OPTI$FDR_ALCOOL <- OPTI$FDRC_alcool

OPTI$ETIO_CMD <- OPTI$FDRC_etio_cmd
OPTI$ETIO_CMT <- OPTI$FDRC_etio_cmt
OPTI$ETIO_CMH <- OPTI$FDRC_etio_cmh
OPTI$ETIO_CMHT <- OPTI$FDRC_etio_cmht
OPTI$ETIO_CMR <- OPTI$FDRC_etio_cmr
OPTI$ETIO_CMV <- OPTI$FDRC_etio_cmv
OPTI$ETIO_CMCONG <- OPTI$FDRC_etio_cmcong
OPTI$ETIO_HTAP <- OPTI$FDRC_etio_htap
OPTI$ETIO_AMY <- OPTI$FDRC_etio_amylose
OPTI$ETIO_CMI <- OPTI$FDRC_cmi
OPTI$ETIO_AUTRE <- OPTI$FDRC_etio_autres

# Antecedents
OPTI$ATCD_FA <- OPTI$ATCD_fa
OPTI$ATCD_DI <- OPTI$ATCD_di
OPTI$ATCD_DYS <- OPTI$ATCD_dysthyroidie
OPTI$ATCD_IDM <- OPTI$ATCD_idm
OPTI$ATCD_ANGIO <- OPTI$ATCD_act
OPTI$ATCD_AVC <- OPTI$ATCD_avc_ait
OPTI$ATCD_CHIR <- OPTI$ATCD_chir_valv
OPTI$ATCD_PAC <- OPTI$ATCD_pac
OPTI$ATCD_HTAP <- OPTI$ATCD_htap
OPTI$ATCD_IR <- OPTI$ATCD_ins_renale
OPTI$ATCD_AOMI <- OPTI$ATCD_aomi
OPTI$ATCD_BPCO <- OPTI$ATCD_bpco
OPTI$ATCD_DEP <- OPTI$ATCD_depression
OPTI$ATCD_APNEE <- OPTI$ATCD_synd_apnee_sommeil
OPTI$ATCD_KC <- OPTI$ATCD_cancer

# Examen
OPTI$FEVG <- OPTI$EXAM_ett_fevg
OPTI$TRST <- OPTI$FRG_score_trst_positif

# Traitements
OPTI$TTT_IEC <- OPTI$TTMT_iec
OPTI$TTT_BB <- OPTI$TTMT_bb
OPTI$TTT_ARA2 <- OPTI$TTMT_ara2
OPTI$TTT_SAC_VAL <- OPTI$TTMT_sacubitril_valsartan
OPTI$TTT_ANTI_ALDO <- OPTI$TTMT_anti_aldosterone
OPTI$TTT_DIU <- OPTI$TTMT_diuretique

# HDJ M1
OPTI$NYHA_M1 <- OPTI$EC_nyha

OPTI$TTT_IEC_M1 <- OPTI$TTMT_iec
OPTI$TTT_BB_M1 <- OPTI$TTMT_bb
OPTI$TTT_ARA2_M1 <- OPTI$TTMT_ara2
OPTI$TTT_SAC_VAL_M1 <- OPTI$TTMT_sacubitril_valsartan
OPTI$TTT_ANTIALDO_M1 <- OPTI$TTMT_anti_aldosterone
OPTI$TTT_DIU_M1 <- OPTI$TTMT_diuretique

OPTI$PRO_KINE_M1 <- OPTI$PROS2_kine
OPTI$PRO_DIET_M1 <- OPTI$PROM1_dieteticien
OPTI$PRO_TABACO_M1 <- OPTI$PROS2_tabacologue
OPTI$PRO_ONCO_M1 <- OPTI$PROS2_oncologue
OPTI$PRO_GER_M1 <- OPTI$PROS2_geriatre
OPTI$PRO_CARDIO_M1 <- OPTI$PROS2_cardiologue
OPTI$PRO_AS_M1 <- OPTI$PROS2_assist_social
OPTI$PRO_ORTHO_M1 <- OPTI$PROS2_orthophoniste
OPTI$PRO_IDE_M1 <- OPTI$PROM1_ide_hdj
OPTI$PRO_REA_CARDIO_M1 <- OPTI$PROS2_readapt_cardiaque

OPTI$ETP_M1 <- OPTI$ETPM1_inf_coord_vue

# Suivi
OPTI$DC <- OPTI$SORT_deces
OPTI$DC[is.na(OPTI$DC)] <- "Non"
OPTI$DESAB <- OPTI$SORT_autre
OPTI$DESAB[is.na(OPTI$DESAB)] <- "Non"

### Selection des variables d'interêt
OPTIM <-  OPTI  %>%
  select(
    ID_STUDY,
    DATE_DEB,
    DATE_NAISSANCE,
    SUIVI,
    AGE,
    TAILLE,
    POIDS_EC,
    IMC,
    PAS,
    PAD,
    NYHA,
    FC,
    FDR_TABAC,
    FDR_DIABETE,
    FDR_DYSLIPIDEMIE,
    FDR_HTA,
    FDR_HEREDITE_CORO,
    FDR_ALCOOL,
    ETIO_CMD,
    ETIO_CMT,
    ETIO_CMH,
    ETIO_CMHT,
    ETIO_CMR,
    ETIO_CMV,
    ETIO_CMCONG,
    ETIO_HTAP,
    ETIO_AMY,
    ETIO_CMI,
    ETIO_AUTRE,
    FEVG,
    TRST,
    TTT_IEC,
    TTT_BB,
    TTT_ARA2,
    TTT_SAC_VAL,
    TTT_ANTI_ALDO,
    TTT_DIU,
    ATCD_FA,
    ATCD_DI,
    ATCD_DYS,
    ATCD_IDM,
    ATCD_ANGIO,
    ATCD_AVC,
    ATCD_CHIR,
    ATCD_PAC,
    ATCD_HTAP,
    ATCD_IR,
    ATCD_AOMI,
    ATCD_BPCO,
    ATCD_DEP,
    ATCD_APNEE,
    ATCD_KC,
    NYHA_M1,
    TTT_IEC_M1,
    TTT_BB_M1,
    TTT_ARA2_M1,
    TTT_SAC_VAL_M1,
    TTT_ANTIALDO_M1,
    TTT_DIU_M1,
    PRO_KINE_M1,
    PRO_DIET_M1,
    PRO_TABACO_M1,
    PRO_ONCO_M1,
    PRO_GER_M1,
    PRO_CARDIO_M1,
    PRO_AS_M1,
    PRO_ORTHO_M1,
    PRO_IDE_M1,
    PRO_REA_CARDIO_M1,
    ETP_M1,
    DATE_SORT,
    DC,
    DESAB
  )
```

```{r, echo=FALSE, include=TRUE}
Symptome$SCORE <- NA
Symptome$SCORE[Symptome$SCORE_score < 12] <- "VERT"
Symptome$SCORE[Symptome$SCORE_score > 11 &
                 Symptome$SCORE_score < 20] <- "ORANGE"
Symptome$SCORE[Symptome$SCORE_score > 19] <- "ROUGE"

### Selection des variables d'intéret
SYMPT <-  Symptome %>%
  select(ID_STUDY,
         SCORE) 
```

```{r, echo=FALSE, include=TRUE}

data <- data.frame(category = c("VERT", "ORANGE", "ROUGE"),
                   count = c(1034, 75, 4))

data$fraction = data$count / sum(data$count)
data$ymax = cumsum(data$fraction)
data$ymin = c(0, head(data$ymax, n = -1))
data$labelPosition <- (data$ymax + data$ymin) / 2
data$label <- paste0("", data$count)

alertes <-
  ggplot(data, aes(
    ymax = ymax,
    ymin = ymin,
    xmax = 4,
    xmin = 3,
    fill = category
  )) +
  geom_rect() +
  geom_label(x = 4,
             aes(y = labelPosition, label = label),
             size = 6) +
  coord_polar(theta = "y") +
  scale_fill_manual(values = c("#FF9966", "#CC3333", "#66CC99")) +
  xlim(c(2, 4)) +
  theme_void() +
  theme(legend.position = "none")
alertes

```

```{r, echo=FALSE, include = TRUE}
Hospit$HOSP_DATE_ENTREE <-
  as.Date(Hospit$HOSP_date_entree, format = "%d/%m/%Y")
Hospit$HOSP_DATE_SORTIE <-
  as.Date(Hospit$HOSP_date_sortiev, format = "%d/%m/%Y")
Hospit$HOSP_DELAI <-
  difftime(Hospit$HOSP_DATE_SORTIE, Hospit$HOSP_DATE_ENTREE, units = "days")
Hospit$HOSP_DELAI <- as.numeric(Hospit$HOSP_DELAI)

Hospit$HOSP_URG <- NA
Hospit$HOSP_URG[Hospit$HOSP_via_urgences == "Non"] <- 0
Hospit$HOSP_URG[Hospit$HOSP_via_urgences == "Oui"] <- 1

Hospit$HOSP <- NA
Hospit$HOSP[Hospit$HOSP_via_urgences == "Non"] <- 1
Hospit$HOSP[Hospit$HOSP_via_urgences == "Oui"] <- 1

Hospit$HOSP_MOTIF <- Hospit$HOSP_motif_ppal

### Selection des variables d'intéret
HOSPIT <-  Hospit %>%
  select(ID_STUDY,
         HOSP_DATE_ENTREE,
         HOSP_DATE_SORTIE,
         HOSP_DELAI,
         HOSP_URG,
         HOSP,
         HOSP_MOTIF) 
```

```{r, echo=FALSE, include = TRUE}
Hosp_ant$HOSPANT_DATE_ENTREE <-
  as.Date(Hosp_ant$HOSPANT_date_entree, format = "%d/%m/%Y")
Hosp_ant$HOSPANT_DATE_SORTIE <-
  as.Date(Hosp_ant$HOSPANT_date_sortie, format = "%d/%m/%Y")
Hosp_ant$HOSPANT_DELAI <-
  difftime(Hosp_ant$HOSPANT_DATE_SORTIE,
           Hosp_ant$HOSPANT_DATE_ENTREE,
           units = "days")
Hosp_ant$HOSPANT_DELAI <- as.numeric(Hosp_ant$HOSPANT_DELAI)

Hosp_ant$HOSPANT_URG <- NA
Hosp_ant$HOSPANT_URG[Hosp_ant$HOSPANT_via_urgences == "Non"] <- 0
Hosp_ant$HOSPANT_URG[Hosp_ant$HOSPANT_via_urgences == "Oui"] <- 1

Hosp_ant$HOSPANT <- NA
Hosp_ant$HOSPANT[Hosp_ant$HOSPANT_via_urgences == "Non"] <- 0
Hosp_ant$HOSPANT[Hosp_ant$HOSPANT_via_urgences == "Oui"] <- 1

Hosp_ant$HOSPANT_MOTIF <- Hosp_ant$HOSPANT_motif_ppal

### Selection des variables d'intéret
HOSPANT <-  Hosp_ant %>%
  select(
    ID_STUDY,
    HOSPANT_DATE_ENTREE,
    HOSPANT_DATE_SORTIE,
    HOSPANT_DELAI,
    HOSPANT_URG,
    HOSPANT,
    HOSPANT_MOTIF
  ) 
```

```{r, echo=FALSE, include = TRUE}
Consult$CONSULT_DATE <-
  as.Date(Consult$CSLT_date_consult, format = "%d/%m/%Y")

Consult$CONSULT <- NA
Consult$CONSULT[Consult$CSLT_via_urgences == "Non"] <- 1
Consult$CONSULT[Consult$CSLT_via_urgences == "Oui"] <- 1

Consult$CONSULT_URG <- NA
Consult$CONSULT_URG[Consult$CSLT_via_urgences == "Non"] <- 0
Consult$CONSULT_URG[Consult$CSLT_via_urgences == "Oui"] <- 1

Consult$CONSULT_MOTIF <- Consult$CSLT_motif_consult
Consult$CONSULT_LIEU <- Consult$CSLT_lieu


### Selection des variables d'intéret
CONSULT <-  Consult %>%
  select(ID_STUDY,
         CONSULT_DATE,
         CONSULT,
         CONSULT_URG,
         CONSULT_MOTIF,
         CONSULT_LIEU) 
```

```{r, echo=FALSE, include=TRUE}
rm(Consult, Hospit, OPTI, Symptome)

CONS_pat <- CONSULT %>%
  group_by(ID_STUDY) %>%
  summarise(
    CONSULT = sum(CONSULT),
    CONSULT_URG = sum(CONSULT_URG),
    CONSULT_CARD = sum(CONSULT_MOTIF == "Cardiaque")
  )

HOSP_pat <- HOSPIT %>%
  group_by(ID_STUDY) %>%
  summarise(
    HOSP = sum(HOSP),
    HOSP_URG = sum(HOSP_URG),
    HOSP_CARD = sum(HOSP_MOTIF == "Cardiaque"),
    HOSP_DUREE = sum(HOSP_DELAI)
  )

HOSPANT_pat <- HOSPANT %>%
  group_by(ID_STUDY) %>%
  summarise(
    HOSPANT = sum(HOSPANT),
    HOSPANT_URG = sum(HOSPANT_URG),
    HOSPANT_CARD = sum(HOSPANT_MOTIF == "Cardiaque"),
    HOSPANT_DUREE = sum(HOSPANT_DELAI)
  )
```

```{r, echo=FALSE, include=TRUE}
MyMerge <- function(x, y) {
  BDD <- merge(x, y, by = "ID_STUDY", all = TRUE)
  return(BDD)
}

df <- Reduce(MyMerge, list(CONSULT, HOSPIT, HOSPANT, OPTIM, SYMPT))
df_pa <-
  Reduce(MyMerge, list(OPTIM, CONS_pat, HOSP_pat, HOSPANT_pat))

df_na <- df_pa %>%
  select(
    ID_STUDY,
    CONSULT,
    CONSULT_URG,
    CONSULT_CARD,
    HOSP,
    HOSP_URG,
    HOSP_CARD,
    HOSPANT,
    HOSPANT_CARD
  )
df_na[is.na(df_na)] <- 0

df_na$CONS <- NA
df_na$CONS[df_na$CONSULT > 0] <- "Oui"
df_na$CONS[df_na$CONSULT == 0] <- "Non"

df_na$HOS <- NA
df_na$HOS[df_na$HOSP > 0] <- "Oui"
df_na$HOS[df_na$HOSP == 0] <- "Non"

df_na$HOSPA <- NA
df_na$HOSPA[df_na$HOSPANT > 0] <- "Oui"
df_na$HOSPA[df_na$HOSPANT == 0] <- "Non"

df_pat <- Reduce(MyMerge, list(OPTIM, df_na))
df_pat$HOSP_DUREE <- df_pa$HOSP_DUREE
df_pat$HOSPANT_DUREE <- df_pa$HOSPANT_DUREE

rm(
  CONS_pat,
  CONSULT,
  df_na,
  df_pa,
  HOSP_pat,
  HOSPIT,
  OPTIM,
  Hosp_ant,
  HOSPANT,
  HOSPANT_pat
)
```

```{r, echo=FALSE, include=TRUE}
table_test <- tableby(
  ~ AGE +
    FDR_TABAC +
    FDR_DIABETE +
    FDR_HTA +
    FDR_DYSLIPIDEMIE +
    FDR_HEREDITE_CORO +
    FDR_ALCOOL +
    ATCD_FA +
    ATCD_DI +
    ATCD_DYS +
    ATCD_IDM +
    ATCD_ANGIO +
    ATCD_AVC +
    ATCD_CHIR +
    ATCD_PAC +
    ATCD_HTAP +
    ATCD_IR +
    ATCD_AOMI +
    ATCD_BPCO +
    ATCD_DEP +
    ATCD_APNEE +
    ATCD_KC,
  df_pat,
  numeric.stats = c("Nmiss", "median", "q1q3")
)


chardem <- summary(table_test,
                   title = "Caractéristiques patient",
                   text = TRUE)
chardem
write.table(chardem,
            'H:/My Drive/Acacia Tools/OPTIMUM/csvdata/Chardem.csv',
            sep = ";")
```

```{r, echo=FALSE, include=TRUE}
table_test <- tableby(
  ~ ETIO_CMD +
    ETIO_CMT +
    ETIO_CMH +
    ETIO_CMHT +
    ETIO_CMR +
    ETIO_CMV +
    ETIO_CMCONG +
    ETIO_HTAP +
    ETIO_AMY +
    ETIO_CMI,
  df_pat,
  numeric.stats = c("Nmiss", "median", "q1q3")
)

etiocardio <- summary(table_test,
                      title = "Etiologie cardiopathie",
                      text = TRUE)
etiocardio

write.table(etiocardio,
            'H:/My Drive/Acacia Tools/OPTIMUM/csvdata/etiocardio.csv',
            sep = ";")
```

```{r, echo=FALSE, include=TRUE}
table_test <- tableby(
  ~ IMC +
    PAS +
    PAD +
    FC +
    NYHA +
    TTT_IEC +
    TTT_BB +
    TTT_ARA2 +
    TTT_SAC_VAL +
    TTT_ANTI_ALDO +
    TTT_DIU +
    HOSPA +
    HOSPANT +
    HOSPANT_CARD +
    HOSPANT_DUREE,
  df_pat,
  numeric.stats = c("Nmiss", "median", "q1q3")
)

clin <- summary(table_test,
                title = "Caractéristiques cliniques à l'entrée",
                text = TRUE)
clin

write.table(clin, 'H:/My Drive/Acacia Tools/OPTIMUM/csvdata/clin_out.csv', sep = ";")
```

```{r, echo=FALSE, include=TRUE}
table_test <- tableby(~ FEVG +
                        TRST,
                      df_pat, numeric.stats = c("Nmiss", "median", "q1q3"))
exam <- summary(table_test,
        title = "Examens",
        text = TRUE)
exam
write.table(exam,'H:/My Drive/Acacia Tools/OPTIMUM/csvdata/exam_out.csv', sep = ";")
```

```{r, echo=FALSE, include=TRUE}
table_test <- tableby( ~ SCORE,
                       SYMPT, numeric.stats = c("Nmiss", "median", "q1q3"))
summary(table_test,
        title = "Alertes",
        text = TRUE)

# write.table(p,'H:/My Drive/Acacia Tools/OPTIMUM/csvdata/table1.csv', sep = ";")
```

```{r, echo=FALSE, include=TRUE}
table_test <- tableby (
  ~ NYHA_M1 +
    TTT_IEC_M1 +
    TTT_BB_M1 +
    TTT_ARA2_M1 +
    TTT_SAC_VAL_M1 +
    TTT_ANTIALDO_M1 +
    TTT_DIU_M1 +
    ETP_M1 +
    PRO_KINE_M1 +
    PRO_DIET_M1 +
    PRO_TABACO_M1 +
    PRO_ONCO_M1 +
    PRO_GER_M1 +
    PRO_CARDIO_M1 +
    PRO_AS_M1 +
    PRO_ORTHO_M1 +
    PRO_IDE_M1 +
    PRO_REA_CARDIO_M1,
  df_pat, numeric.stats = c("Nmiss", "median", "q1q3"))

hdj <- summary(table_test,
               title = "HDJ M1",
               text = TRUE)
hdj
write.table(hdj, 'H:/My Drive/Acacia Tools/OPTIMUM/csvdata/hdj_out.csv', sep = ";")
```

```{r, echo=FALSE, include=TRUE}
table_test <- tableby (
  ~ CONS +
    CONSULT  +
    CONSULT_URG +
    CONSULT_CARD +
    HOS +
    HOSP +
    HOSP_URG +
    HOSP_CARD +
    HOSP_DUREE +
    DC +
    DESAB +
    SUIVI,
  df_pat, numeric.stats = c("Nmiss", "median", "q1q3"))

hosp <- summary(table_test,
                title = "Consultations & hospitalisations",
                text = TRUE)
hosp
write.table(hosp, 'H:/My Drive/Acacia Tools/OPTIMUM/csvdata/hosp_out.csv', sep = ";")
```

```{r, echo=FALSE, include=TRUE}
graph <-
  data.frame (
    Evaluation  = c(
      "Baseline",
      "Baseline",
      "Baseline",
      "Baseline",
      "Baseline",
      "Baseline",
      "HDJ",
      "HDJ",
      "HDJ",
      "HDJ",
      "HDJ",
      "HDJ"
    ),
    Traitements = c(
      "IEC",
      "BB",
      "ARA2",
      "SAC / VAL",
      "ANTI-ALDO",
      "Diurétique",
      "IEC",
      "BB",
      "ARA2",
      "SAC / VAL",
      "ANTI-ALDO",
      "Diurétique"
    ),
    N = c(22, 46, 9, 7, 1, 56, 14, 20, 2, 1, 0, 28),
    Pct = c(33, 69, 13, 10, 2, 84, 45, 65, 7, 3,0,90)
  )


graph$Evaluation <-
  factor(graph$Evaluation, levels = c("Baseline", "HDJ"))

p <- ggplot(graph, aes(x = Traitements, y = Pct)) +
  geom_col(aes(fill = Evaluation),
           position = position_dodge(0.8),
           width = 0.7)  +
  theme_light() +
  labs(x = "Traitements", y = "Effectif (%)", title = "") +
  theme(
    axis.text.x = element_text(color = "black", size = 10),
    axis.text.y = element_text(color = "black", size = 10),
    axis.title.x = element_text(
      colour = "black",
      size = 10,
      face = "bold"
    ),
    axis.title.y = element_text(
      colour = "black",
      size = 10,
      face = "bold"
    )
  ) +
  scale_y_continuous(breaks = c(0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100)) +
  scale_fill_brewer(palette = "Set2")
p

```

